# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ResourcesNow
title_separator: "|"
subtitle: Because I can't organize my bookmarks
logo: "/assets/images/logo.png"
# Repo info
repository: MGOPW/SNResourcesNow
email:
description: >- # this means to ignore newlines until "baseurl:"
  Simple index for all ServiceNow resources created by it's amazing community.
minimal_mistakes_skin: "mint"
search: true
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
remote_theme: mmistakes/minimal-mistakes
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages
  - assets
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-tagories
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
author:
  name   : "MGOPW"
  avatar : "/assets/images/mgopw.png"
  bio    : "She/Her || 2021 ServiceNow Developer MVP."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mgopw"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/theRealMGOPW"  
footer:
  links:
    - label: "Contribute"
      icon: "fas fa-file-alt"
      url: "https://github.com/MGOPW/SNResourcesNow"
    - label: "snDevs Slack"
      icon: "fas fa-slack"
      url: "https://sndevs.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false  
      excerpt: ""
      sidebar:
        nav: "side"
  # _blogs
  - scope:
      path: ""
      type: blogs
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _repos
  - scope:
      path: ""
      type: repos
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _official
  - scope:
      path: ""
      type: official
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _podcasts
  - scope:
      path: ""
      type: podcasts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _people
  - scope:
      path: ""
      type: people
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _misc
  - scope:
      path: ""
      type: misc
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
collections_dir: items

collections:
  blogs:
    output: true
    permalink: /:collection/:path/
  repos:
    output: true
    permalink: /:collection/:path/
  official:
    output: true
    permalink: /:collection/:path/
  podcasts:
    output: true
    permalink: /:collection/:path/ 
  people:
    output: true
    permalink: /:collection/:path/
  misc:
    output: true
    permalink: /:collection/:path/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.

og_image: /assets/images/logo.png

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-EJK7LDVCWX"
    anonymize_ip: false # default